meta:
  schema_version: 3
hosts:
  all:
    - ssh_target: ssh://demo@127.0.0.1:2222
      ssh_password: demo
      sudo_password: demo
plays:
  - name: Test
    hosts: [all]
    tasks:
      - name: date
        command:
          cmd: sh -c "date >> /now"
      - name: id
        command:
          cmd: sh -c "id >> /now"
